<script id="tailwind-config">
    tailwind.config = {
        darkMode: 'class',
        theme: {
            extend: {
                colors: {
                    primary: '#864d61',
                    'on-primary': '#ffffff',
                    'on-primary-fixed': '#360b1e',
                    'on-primary-fixed-variant': '#6a364a',
                    'on-primary-container': '#7b4458',
                    'primary-container': '#ffb7ce',
                    'primary-fixed': '#ffd9e3',
                    'primary-fixed-dim': '#fab3ca',
                    'inverse-primary': '#fab3ca',
                    secondary: '#346664',
                    'on-secondary': '#ffffff',
                    'on-secondary-container': '#386b69',
                    'on-secondary-fixed': '#00201f',
                    'on-secondary-fixed-variant': '#194e4d',
                    'secondary-container': '#b5eae6',
                    'secondary-fixed': '#b8ece9',
                    'secondary-fixed-dim': '#9cd0cd',
                    tertiary: '#725c00',
                    'on-tertiary': '#ffffff',
                    'on-tertiary-container': '#675300',
                    'on-tertiary-fixed': '#231b00',
                    'on-tertiary-fixed-variant': '#564500',
                    'tertiary-container': '#e9c85d',
                    'tertiary-fixed': '#ffe080',
                    'tertiary-fixed-dim': '#e4c45a',
                    background: '#fff8f5',
                    'on-background': '#291806',
                    surface: '#fff8f5',
                    'on-surface': '#291806',
                    'on-surface-variant': '#514347',
                    'surface-variant': '#fedcbe',
                    'surface-bright': '#fff8f5',
                    'surface-dim': '#f6d4b6',
                    'surface-tint': '#864d61',
                    'surface-container': '#ffeada',
                    'surface-container-low': '#fff1e7',
                    'surface-container-lowest': '#ffffff',
                    'surface-container-high': '#ffe3cc',
                    'surface-container-highest': '#fedcbe',
                    'inverse-surface': '#402c18',
                    'inverse-on-surface': '#ffeee0',
                    outline: '#837377',
                    'outline-variant': '#d5c2c6',
                    error: '#ba1a1a',
                    'on-error': '#ffffff',
                    'error-container': '#ffdad6',
                    'on-error-container': '#93000a',
                },
                borderRadius: {
                    DEFAULT: '1rem',
                    lg: '2rem',
                    xl: '3rem',
                    full: '9999px',
                },
                spacing: {
                    gutter: '24px',
                    base: '8px',
                    md: '24px',
                    xl: '80px',
                    'margin-mobile': '16px',
                    lg: '48px',
                    'margin-desktop': '64px',
                    xs: '4px',
                    sm: '12px',
                },
                fontFamily: {
                    'headline-sm': ['Plus Jakarta Sans'],
                    'label-md': ['Inter'],
                    'display-lg-mobile': ['Plus Jakarta Sans'],
                    'body-lg': ['Inter'],
                    'display-lg': ['Plus Jakarta Sans'],
                    'headline-md': ['Plus Jakarta Sans'],
                    'body-md': ['Inter'],
                    'label-sm': ['Inter'],
                },
                fontSize: {
                    'headline-sm': ['24px', { lineHeight: '32px', fontWeight: '700' }],
                    'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
                    'display-lg-mobile': ['36px', { lineHeight: '42px', letterSpacing: '-0.01em', fontWeight: '800' }],
                    'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
                    'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '800' }],
                    'headline-md': ['32px', { lineHeight: '40px', fontWeight: '700' }],
                    'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
                    'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
                },
            },
        },
    };
</script>
